Added new 3 time keeping features
opengamedata/ogd-core pull request #243
Opened 2024-11-27 22:50 UTC by smitpatel8

Added the 3 time keeping features TotalSessionTime, TotalPopulationTime and TotalPlayerTime.

2024-12-09 01:24 UTC, LswaN58 requested changes
Features all look very good, just a couple minor adjustments and we're good to go.

2024-12-09 01:24 UTC, LswaN58 commented on src/ogd/games/AQUALAB/features/TotalPopulationTime.py
> +    def Subfeatures(self) -> List[str]:
Same as TotalPlayerTime, don't need "Total" subfeature.

2024-12-09 01:24 UTC, LswaN58 commented on src/ogd/games/AQUALAB/features/TotalSessionTime.py
> +    def Subfeatures(self) -> List[str]:
Same as TotalPlayerTime, don't need "Total" subfeature.

2024-12-09 01:24 UTC, LswaN58 commented on src/ogd/games/AQUALAB/schemas/AQUALAB.json.template
> -                "description": "An indicator of whether play happened during normal school hours or not",
Keep original description

2025-02-20 17:43 UTC, vijayrampatel commented
• `FollowedAdvice` - Tracks if the player has switched to the advised job
• `SurveyCompleted` - Monitors survey submission status across multiple instruments  
• `JobRecommendationReceived` - keep track of the recommendations received during the session
• `LeftJob`- Tracks if the player has left the job
• `SuccessfulAdvice` - Tracks if a player has followed the advice to do another job and came back to the original job
• `ExperimentalCondition` - Returns the branch version

2025-02-25 17:05 UTC, LswaN58 requested changes
We're in mostly good shape, but there are some changes to make, in addition to some new GH issue cards to implement.

2025-02-25 17:05 UTC, LswaN58 commented on src/ogd/games/AQUALAB/features/__init__.py
We're missing ExperimentalCondition, FollowedAdvice, SuccessfulAdvice, and SurveyCompleted from the `__all__` array. We'll need to add those.

2025-02-27 18:40 UTC, LswaN58 requested changes
I need to make change based on comment I tagged myself in.

2025-03-13 00:43 UTC, LswaN58 approved these changes

2025-03-13 00:43 UTC, merged